# version: '29.4.0'

services:
  web:
    build: .
    command: python /code/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
    working_dir: /code
    stdin_open: true
    tty: true
    depends_on:
      - db
    restart: on-failure

  db:
    image: postgres:18
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
    ports:
      - "5432:5432"

