# Generated by Django 6.0.2 on 2026-08-20 07:22

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', ckeditor.fields.RichTextField(verbose_name='text')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='last updated')),
            ],
            options={
                'verbose_name': 'about_us',
                'verbose_name_plural': 'about_us_plural',
            },
        ),
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(verbose_name='address')),
                ('postal_code', models.CharField(max_length=20, verbose_name='postal cart')),
                ('phone', models.CharField(max_length=20, verbose_name='phone')),
                ('whatsapp', models.CharField(max_length=50, null=True, verbose_name='whatsapp')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
            ],
            options={
                'verbose_name': 'contact_info',
                'verbose_name_plural': 'contact_infos',
            },
        ),
        migrations.CreateModel(
            name='CooperationInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intro_text', ckeditor.fields.RichTextField(verbose_name='intro_text')),
                ('invitation_text', ckeditor.fields.RichTextField(verbose_name='invitation_text')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='last updated')),
            ],
            options={
                'verbose_name': 'cooperation',
                'verbose_name_plural': 'cooperations',
            },
        ),
        migrations.CreateModel(
            name='OrderCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', ckeditor.fields.RichTextField(verbose_name='text')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'orderus',
                'verbose_name_plural': 'orderus',
            },
        ),
    ]
