# Generated by Django 6.0.2 on 2026-09-24 09:51

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SitePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wordpress_id', models.PositiveIntegerField(db_index=True, unique=True)),
                ('title', models.CharField(max_length=250)),
                ('slug', models.SlugField(allow_unicode=True, max_length=250, unique=True)),
                ('content', ckeditor.fields.RichTextField(blank=True)),
                ('excerpt', models.TextField(blank=True)),
                ('source', models.CharField(choices=[('page', 'WordPress page'), ('post', 'WordPress post')], default='page', max_length=20)),
                ('status', models.CharField(default='publish', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('datetime_created', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'archived page',
                'verbose_name_plural': 'archived pages',
                'ordering': ['title'],
            },
        ),
    ]
