# Generated by Django 6.0.2 on 2026-07-11 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CooperationInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intro_text', models.TextField(default='انتشارات کتابکده کسری با نگاه ویژه به جریان روز معماری و رشته\u200cهای وابسته، با اساتید، دانش\u200cپژوهان و صاحب\u200cنظران همکاری می\u200cنماید تا با انتشار آثار تالیف و ترجمه، از تولید محتوای ارزشمند حمایت نماید.', verbose_name='متن معرفی')),
                ('convergence_text', models.TextField(default='همگرایی نگاه\u200cهای منتوع، اساس دگرگونی و رشد است. از این رو ما از ایده\u200cهای نو و تعریف پروژه\u200cهای جدید در حوزه فعالیت\u200cهای انتشارات پشتیبانی کرده؛ توان و تجربه خود را برای تحقق ایده\u200cها و مشارکت در پروژه\u200cها، در اختیار صاحبان ایده قرار می\u200cدهیم.', verbose_name='متن همگرایی')),
                ('documentation_text', models.TextField(default='نظر به ضرورت مستندسازی فعالیت\u200cهای آموزشی، پژوهشی و حرفه\u200cای، ما به عنوان نهاد نشر و بخشی از جامعه معماری، با سایر نهادها و ارکان حرفه\u200cای رسمی و خصوصی گوناگون همکاری نموده و از گسترش این ارتباطات در جهت انعکاس فعالیت\u200cها و دستاوردها استقبال می\u200cنماییم.', verbose_name='متن مستندسازی')),
                ('collaboration_text', models.TextField(default='برای مشاوره و همکاری در انتشار آثار ترجمه و تألیف، اجرای پروژه\u200cهای نشر و مستندسازی فعالیت\u200cهای آموزشی، پژوهشی و حرفه\u200cای، ما در کنار شما هستیم. با ما در ارتباط باشید...', verbose_name='متن مشاوره و همکاری')),
                ('invitation_text', models.TextField(default='همچنین این انتشارات از تمامی افراد خلاق و علاقه\u200cمند به نشر و تولید محتوا، اعم از گرافیست، ویراستار تخصصی و متخصصین رسانه\u200cهای دیجیتال دعوت به همکاری می\u200cنماید. برای ثبت درخواست همکاری، مشخصات، رزومه و نوع علاقه کاری خود را به آدرس ایمیل زیر ارسال نمایید.', verbose_name='متن دعوت به همکاری')),
                ('email', models.EmailField(default='kasrapublishing@gmail.com', max_length=254, verbose_name='ایمیل')),
                ('is_active', models.BooleanField(default=True, help_text='در صورت غیرفعال بودن، صفحه همکاری نمایش داده نمی\u200cشود', verbose_name='فعال')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
            ],
            options={
                'verbose_name': 'محتوای صفحه همکاری',
                'verbose_name_plural': 'محتوای صفحه همکاری',
            },
        ),
        migrations.AlterModelOptions(
            name='contactinfo',
            options={'verbose_name': ' contact_info', 'verbose_name_plural': 'contact_info'},
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='address',
            field=models.TextField(verbose_name='address'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='phone'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='postal_code',
            field=models.CharField(max_length=20, verbose_name='postal_cart '),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='whatsapp',
            field=models.CharField(max_length=20, verbose_name='whatsapp'),
        ),
    ]
