# Generated by Django 6.0.2 on 2026-07-11 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_cooperationinfo_alter_contactinfo_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactinfo',
            options={'verbose_name': 'contact_info', 'verbose_name_plural': 'contact_info'},
        ),
    ]
