# Generated by Django 6.0.2 on 2026-07-11 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_alter_contactinfo_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactinfo',
            options={'verbose_name': 'اطلاعات تماس', 'verbose_name_plural': 'اطلاعات تماس'},
        ),
        migrations.RemoveField(
            model_name='cooperationinfo',
            name='collaboration_text',
        ),
        migrations.RemoveField(
            model_name='cooperationinfo',
            name='convergence_text',
        ),
        migrations.RemoveField(
            model_name='cooperationinfo',
            name='documentation_text',
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='address',
            field=models.TextField(verbose_name='آدرس'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='ایمیل'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='تلفن'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='postal_code',
            field=models.CharField(max_length=20, verbose_name='کد پستی'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='whatsapp',
            field=models.CharField(max_length=20, verbose_name='واتساپ'),
        ),
    ]
