# Generated by Django 6.0.2 on 2026-07-11 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_alter_contactinfo_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactinfo',
            options={'verbose_name': 'contact_info', 'verbose_name_plural': 'contact_infos'},
        ),
        migrations.AlterModelOptions(
            name='cooperationinfo',
            options={'verbose_name': 'cooperation', 'verbose_name_plural': 'cooperations'},
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='address',
            field=models.TextField(verbose_name='address'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='phone'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='postal_code',
            field=models.CharField(max_length=20, verbose_name='postal cart'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='whatsapp',
            field=models.CharField(max_length=20, verbose_name='whatsapp'),
        ),
        migrations.AlterField(
            model_name='cooperationinfo',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='cooperationinfo',
            name='intro_text',
            field=models.TextField(verbose_name='intro_text'),
        ),
        migrations.AlterField(
            model_name='cooperationinfo',
            name='invitation_text',
            field=models.TextField(verbose_name='invitation_text'),
        ),
        migrations.AlterField(
            model_name='cooperationinfo',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='cooperationinfo',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='last updated'),
        ),
    ]
