# Generated by Django 6.0.2 on 2026-07-11 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_alter_contactinfo_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cooperationinfo',
            name='email',
        ),
    ]
