# Generated by Django 6.0.2 on 2026-07-12 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_alter_aboutus_options_aboutus_is_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='text')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'order condition',
                'verbose_name_plural': 'order conditions',
            },
        ),
    ]
