# Generated by Django 6.0.2 on 2026-07-12 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_ordercondition'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordercondition',
            options={'verbose_name': 'orderus', 'verbose_name_plural': 'orderus'},
        ),
    ]
