# Generated by Django 6.0.2 on 2026-07-12 09:17

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_alter_ordercondition_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='text',
            field=ckeditor.fields.RichTextField(verbose_name='text'),
        ),
        migrations.AlterField(
            model_name='cooperationinfo',
            name='invitation_text',
            field=ckeditor.fields.RichTextField(verbose_name='invitation_text'),
        ),
        migrations.AlterField(
            model_name='ordercondition',
            name='text',
            field=ckeditor.fields.RichTextField(verbose_name='text'),
        ),
    ]
