# Generated by Django 6.0.2 on 2026-07-12 09:25

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_alter_aboutus_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cooperationinfo',
            name='intro_text',
            field=ckeditor.fields.RichTextField(verbose_name='intro_text'),
        ),
    ]
