# Generated by Django 6.0.2 on 2026-08-08 07:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_alter_cooperationinfo_intro_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactinfo',
            name='whatsapp',
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='mobile',
            field=models.CharField(default=django.utils.timezone.now, max_length=20, verbose_name='mobile'),
            preserve_default=False,
        ),
    ]
