# Generated by Django 6.0.2 on 2026-08-08 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_remove_contactinfo_whatsapp_contactinfo_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinfo',
            name='mobile',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
