# Generated by Django 6.0.2 on 2026-08-08 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_alter_contactinfo_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinfo',
            name='mobile',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='mobile'),
        ),
    ]
