# Generated by Django 6.0.2 on 2026-08-08 07:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0015_alter_contactinfo_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinfo',
            name='mobile',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[django.core.validators.RegexValidator(message='شماره موبایل معتبر نیست.', regex='^[\\+]?[(]?[0-9]{3}[)]?[-\\s\\.]?[0-9]{3}[-\\s\\.]?[0-9]{4,6}$')], verbose_name='mobile'),
        ),
    ]
