# Generated by Django 6.0.2 on 2026-08-08 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0016_alter_contactinfo_mobile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactinfo',
            name='mobile',
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='whatsapp',
            field=models.CharField(max_length=20, null=True, verbose_name='whatsapp'),
        ),
    ]
