# Generated by Django 6.0.2 on 2026-08-08 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0017_remove_contactinfo_mobile_contactinfo_whatsapp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinfo',
            name='whatsapp',
            field=models.CharField(max_length=50, null=True, verbose_name='whatsapp'),
        ),
    ]
