# Generated by Django 6.0.2 on 2026-08-08 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0018_alter_contactinfo_whatsapp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactinfo',
            name='whatsapp',
        ),
    ]
