# Generated by Django 6.0.2 on 2026-08-20 07:47

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='address',
            field=models.TextField(blank=True, help_text='آدرس پستی', verbose_name='address'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='birth_date',
            field=models.DateField(blank=True, help_text='تاریخ تولد برای پیامک تبریک', null=True, verbose_name='birth date'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='شماره موبایل برای ارسال پیامک تخفیف', max_length=128, null=True, region=None, verbose_name='phone number'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='postal_code',
            field=models.CharField(blank=True, help_text='کد پستی', max_length=20, verbose_name='postal code'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='wallet_balance',
            field=models.PositiveIntegerField(default=0, help_text='موجودی کیف پول (تومان)', verbose_name='wallet balance'),
        ),
    ]
