# Generated by Django 6.0.2 on 2026-08-23 07:09

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_address_customuser_birth_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='address',
            field=models.TextField(blank=True, help_text='postal address', verbose_name='address'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='birth_date',
            field=models.DateField(blank=True, help_text='birth date for birthday SMS', null=True, verbose_name='birth date'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='mobile number for discount SMS', max_length=128, null=True, region=None, verbose_name='phone number'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='postal_code',
            field=models.CharField(blank=True, help_text='postal code', max_length=20, verbose_name='postal code'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='wallet_balance',
            field=models.PositiveIntegerField(default=0, help_text='wallet balance in Toman', verbose_name='wallet balance'),
        ),
    ]
