# Generated by Django 6.0.2 on 2026-08-24 08:30

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_address_alter_customuser_birth_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='address',
            field=models.TextField(blank=True, verbose_name='address'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='birth_date',
            field=models.CharField(blank=True, help_text='Format: 1370/05/15', max_length=10, verbose_name='birth date'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='phone number'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20, verbose_name='postal code'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='wallet_balance',
            field=models.PositiveIntegerField(default=0, verbose_name='wallet balance'),
        ),
    ]
