# Generated by Django 6.0.2 on 2026-09-24 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_customuser_address_alter_customuser_birth_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='wordpress_id',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True, unique=True, verbose_name='wordpress id'),
        ),
    ]
