# Generated by Django 6.0.2 on 2026-08-20 07:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_price',
            field=models.PositiveIntegerField(default=0, help_text='مبلغ کل سفارش (تومان)', verbose_name='total price'),
        ),
        migrations.AddField(
            model_name='order',
            name='total_weight',
            field=models.PositiveIntegerField(default=0, help_text='وزن کل سفارش (گرم)', verbose_name='total weight'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='products.package'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='products.product'),
        ),
    ]
