# Generated by Django 6.0.2 on 2026-08-26 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_returnrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='installment_plan_id',
            field=models.CharField(blank=True, max_length=20, verbose_name='installment plan'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('online', 'Online'), ('installment', 'Installment')], default='online', max_length=20, verbose_name='payment method'),
        ),
    ]
