# Generated by Django 6.0.2 on 2026-09-24 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_order_datetime_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='wordpress_id',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True, unique=True, verbose_name='wordpress id'),
        ),
    ]
