# Generated by Django 6.0.2 on 2026-08-18 08:56

import ckeditor.fields
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='product_title')),
                ('category', models.CharField(choices=[('BUSINESS', 'BUSINESS'), ('ARCH_DESIGN', 'ARCH_DESIGN'), ('INTERIOR', 'INTERIOR'), ('URBAN', 'URBAN'), ('LANDSCAPE', 'LANDSCAPE'), ('DESIGN_GUIDE', 'DESIGN_GUIDE'), ('HISTORY', 'HISTORY'), ('DESIGN_BASICS', 'DESIGN_BASICS'), ('DIGITAL', 'DIGITAL'), ('SUSTAIN', 'SUSTAIN'), ('SAMPLES', 'SAMPLES'), ('OTHER', 'OTHER'), ('PACKAGES', 'PACKAGES')], default='OTHER', max_length=50, verbose_name='product_category')),
                ('description', ckeditor.fields.RichTextField(verbose_name='description')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='price')),
                ('active', models.BooleanField(default=True, verbose_name='active')),
                ('image', models.ImageField(blank=True, upload_to='product/product_cover/', verbose_name='image')),
                ('author', models.CharField(blank=True, max_length=200, verbose_name='author')),
                ('publisher', models.CharField(blank=True, max_length=200, verbose_name='publisher')),
                ('isbn', models.CharField(blank=True, max_length=20, verbose_name='isbn')),
                ('year_of_publication', models.IntegerField(blank=True, null=True, verbose_name='year_of_publication')),
                ('edition', models.CharField(blank=True, max_length=50, verbose_name='edition')),
                ('number_of_pages', models.IntegerField(blank=True, null=True, verbose_name='number_of_pages')),
                ('book_size', models.CharField(blank=True, choices=[('raghiei', 'رقعی'), ('vazehi', 'وزیری'), ('jeybi', 'جیبی'), ('rahlei', 'رحلی'), ('other', 'سایر')], max_length=20, null=True, verbose_name='book_size')),
                ('cover_type', models.CharField(blank=True, choices=[('shomiz', 'شومیز'), ('gard', 'گالینگور'), ('other', 'سایر')], max_length=20, null=True, verbose_name='cover_type')),
                ('publication_date', models.IntegerField(blank=True, null=True, verbose_name='publication_date')),
                ('printing_series', models.CharField(blank=True, max_length=100, null=True, verbose_name='printing_series')),
                ('weight', models.IntegerField(blank=True, null=True, verbose_name='weight')),
                ('discount_percent', models.PositiveSmallIntegerField(default=0, help_text='درصد تخفیف (0 تا 100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='discount percent')),
                ('discount_start_date', models.DateTimeField(blank=True, help_text='زمان شروع تخفیف', null=True, verbose_name='discount start date')),
                ('discount_end_date', models.DateTimeField(blank=True, help_text='زمان پایان تخفیف', null=True, verbose_name='discount end date')),
                ('special_price', models.PositiveIntegerField(default=0, help_text='قیمت ویژه (اگر وارد شود، تخفیف به صورت مبلغ ثابت اعمال می\u200cشود)', validators=[django.core.validators.MinValueValidator(0)], verbose_name='special price')),
                ('datetime_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='datetime_created')),
                ('datetime_modified', models.DateTimeField(auto_now=True, verbose_name='datetime_modified')),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('slug', models.SlugField(allow_unicode=True, max_length=200, unique=True, verbose_name='slug')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('image', models.ImageField(blank=True, null=True, upload_to='packages/', verbose_name='image')),
                ('original_price', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='original price')),
                ('price', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='price')),
                ('discount_percent', models.PositiveSmallIntegerField(default=0, help_text='Discount percentage (if set, price will be auto-calculated)', verbose_name='discount percent')),
                ('manual_price', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='manual price')),
                ('stock', models.PositiveIntegerField(default=0, help_text='Available stock for this package', validators=[django.core.validators.MinValueValidator(0)], verbose_name='stock')),
                ('active', models.BooleanField(default=True, verbose_name='active')),
                ('datetime_created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('datetime_modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('products', models.ManyToManyField(blank=True, limit_choices_to={'active': True}, related_name='packages', to='products.product', verbose_name='products')),
            ],
            options={
                'verbose_name': 'package',
                'verbose_name_plural': 'packages',
                'ordering': ['-datetime_created'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(verbose_name='Comment_Text')),
                ('stars', models.IntegerField(choices=[(1, 'Very_Bad'), (2, 'Bad'), (3, 'Normal'), (4, 'Good'), (5, 'Perfect')], verbose_name='What_is_your_score?')),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('detetime_modified', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True, verbose_name='Comment_Active')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='comment_author')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='products.product', verbose_name='Comment_Product')),
            ],
        ),
    ]
