# Generated by Django 6.0.2 on 2026-08-22 07:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='reserved_stock',
            field=models.PositiveIntegerField(default=0, verbose_name='reserved stock'),
        ),
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(default=0, verbose_name='stock'),
        ),
        migrations.AlterField(
            model_name='package',
            name='discount_percent',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='discount percent'),
        ),
        migrations.AlterField(
            model_name='package',
            name='stock',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='stock'),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount_end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='discount end date'),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount_percent',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='discount percent'),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount_start_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='discount start date'),
        ),
        migrations.AlterField(
            model_name='product',
            name='special_price',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='special price'),
        ),
    ]
