# Generated by Django 6.0.2 on 2026-08-22 07:44

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_reserved_stock_product_stock_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='code')),
                ('percent', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='percent')),
                ('amount', models.PositiveIntegerField(default=0, help_text='مبلغ تخفیف ثابت (تومان)', verbose_name='amount')),
                ('max_uses', models.PositiveIntegerField(default=1, verbose_name='max uses')),
                ('used_count', models.PositiveIntegerField(default=0, verbose_name='used count')),
                ('active', models.BooleanField(default=True, verbose_name='active')),
                ('valid_from', models.DateTimeField(blank=True, null=True, verbose_name='valid from')),
                ('valid_until', models.DateTimeField(blank=True, null=True, verbose_name='valid until')),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='stock',
            field=models.PositiveIntegerField(default=0, help_text='موجودی انبار', validators=[django.core.validators.MinValueValidator(0)], verbose_name='stock'),
        ),
        migrations.CreateModel(
            name='TieredDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_tier', models.PositiveSmallIntegerField(default=0, verbose_name='current tier')),
                ('datetime_updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiered_discounts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
