# Generated by Django 6.0.2 on 2026-08-22 07:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_discountcode_comment_stock_tiereddiscount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='stock',
        ),
        migrations.AlterField(
            model_name='product',
            name='reserved_stock',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='reserved stock'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='stock'),
        ),
    ]
