# Generated by Django 6.0.2 on 2026-08-25 09:29

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_comment_stock_alter_product_reserved_stock_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstallmentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_count', models.PositiveSmallIntegerField(default=3, verbose_name='month count')),
                ('prepayment_percent', models.PositiveSmallIntegerField(default=30, help_text='Prepayment percentage', verbose_name='prepayment percent')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installment_plans', to='products.product', verbose_name='product')),
            ],
            options={
                'verbose_name': 'Installment Plan',
                'verbose_name_plural': 'Installment Plans',
            },
        ),
        migrations.CreateModel(
            name='ProductBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('content', ckeditor.fields.RichTextField(verbose_name='content')),
                ('blog_type', models.CharField(choices=[('ARTICLE', 'Article'), ('NEWS', 'News'), ('STORY', 'Story')], default='ARTICLE', max_length=20, verbose_name='type')),
                ('video', models.FileField(blank=True, help_text='Upload video file', null=True, upload_to='products/videos/', verbose_name='video')),
                ('author_name', models.CharField(blank=True, max_length=200, verbose_name='author name')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('datetime_created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('datetime_updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blogs', to='products.product', verbose_name='product')),
            ],
            options={
                'verbose_name': 'Product Blog',
                'verbose_name_plural': 'Product Blogs',
                'ordering': ['-datetime_created'],
            },
        ),
    ]
