# Generated by Django 6.0.2 on 2026-08-26 08:01

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_installmentplan_productblog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='detetime_modified',
            new_name='datetime_modified',
        ),
        migrations.AlterField(
            model_name='comment',
            name='active',
            field=models.BooleanField(default=True, verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='author'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='body',
            field=models.TextField(verbose_name='comment text'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='products.product', verbose_name='product'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='stars',
            field=models.IntegerField(choices=[(1, 'Very Bad'), (2, 'Bad'), (3, 'Normal'), (4, 'Good'), (5, 'Perfect')], verbose_name='rating'),
        ),
        migrations.AlterField(
            model_name='discountcode',
            name='amount',
            field=models.PositiveIntegerField(default=0, verbose_name='amount'),
        ),
        migrations.AlterField(
            model_name='installmentplan',
            name='prepayment_percent',
            field=models.PositiveSmallIntegerField(default=30, verbose_name='prepayment percent'),
        ),
        migrations.AlterField(
            model_name='product',
            name='book_size',
            field=models.CharField(blank=True, choices=[('raghiei', 'Raghei'), ('vazehi', 'Vazehi'), ('jeybi', 'Jeybi'), ('rahlei', 'Rahlei'), ('other', 'Other')], max_length=30, null=True, verbose_name='book size'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('BUSINESS', 'BUSINESS'), ('ARCH_DESIGN', 'ARCH_DESIGN'), ('INTERIOR', 'INTERIOR'), ('URBAN', 'URBAN'), ('LANDSCAPE', 'LANDSCAPE'), ('DESIGN_GUIDE', 'DESIGN_GUIDE'), ('HISTORY', 'HISTORY'), ('DESIGN_BASICS', 'DESIGN_BASICS'), ('DIGITAL', 'DIGITAL'), ('SUSTAIN', 'SUSTAIN'), ('SAMPLES', 'SAMPLES'), ('OTHER', 'OTHER'), ('PACKAGES', 'PACKAGES')], default='OTHER', max_length=50, verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='cover_type',
            field=models.CharField(blank=True, choices=[('shomiz', 'Shomiz'), ('gard', 'Gard'), ('other', 'Other')], max_length=30, null=True, verbose_name='cover type'),
        ),
        migrations.AlterField(
            model_name='product',
            name='datetime_created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='product',
            name='datetime_modified',
            field=models.DateTimeField(auto_now=True, verbose_name='modified'),
        ),
        migrations.AlterField(
            model_name='product',
            name='number_of_pages',
            field=models.IntegerField(blank=True, null=True, verbose_name='number of pages'),
        ),
        migrations.AlterField(
            model_name='product',
            name='printing_series',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='printing series'),
        ),
        migrations.AlterField(
            model_name='product',
            name='publication_date',
            field=models.IntegerField(blank=True, null=True, verbose_name='publication date'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=200, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='product',
            name='year_of_publication',
            field=models.IntegerField(blank=True, null=True, verbose_name='year of publication'),
        ),
        migrations.AlterField(
            model_name='productblog',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='products/videos/', verbose_name='video'),
        ),
    ]
