# Generated by Django 6.0.2 on 2026-08-26 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_rename_detetime_modified_comment_datetime_modified_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='datetime_modified',
            new_name='detetime_modified',
        ),
    ]
