# Generated by Django 6.0.2 on 2026-05-31 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_short_discription_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='short_discription',
            field=models.TextField(blank=True),
        ),
    ]
