# Generated by Django 6.0.2 on 2026-08-26 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_faq'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='related_questions',
            field=models.ManyToManyField(blank=True, help_text='Questions to suggest after this answer', related_name='related_to', to='products.faq', verbose_name='related questions'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='display order'),
        ),
    ]
