# Generated by Django 6.0.2 on 2026-09-02 09:53

import django.core.validators
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_faq_related_questions_alter_faq_order'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-datetime_created'], 'verbose_name': 'comment', 'verbose_name_plural': 'comments'},
        ),
        migrations.AlterModelOptions(
            name='discountcode',
            options={'ordering': ['-datetime_created'], 'verbose_name': 'discount code', 'verbose_name_plural': 'discount codes'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-datetime_created'], 'verbose_name': 'product', 'verbose_name_plural': 'products'},
        ),
        migrations.AlterModelOptions(
            name='tiereddiscount',
            options={'verbose_name': 'tiered discount', 'verbose_name_plural': 'tiered discounts'},
        ),
        migrations.RemoveField(
            model_name='comment',
            name='detetime_modified',
        ),
        migrations.AddField(
            model_name='comment',
            name='datetime_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='datetime_created',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='stars',
            field=models.IntegerField(choices=[(1, 'Very Bad'), (2, 'Bad'), (3, 'Normal'), (4, 'Good'), (5, 'Perfect')], db_index=True, verbose_name='rating'),
        ),
        migrations.AlterField(
            model_name='discountcode',
            name='active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='discountcode',
            name='code',
            field=models.CharField(db_index=True, max_length=50, unique=True, verbose_name='code'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='display order'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='question',
            field=models.CharField(db_index=True, max_length=300, verbose_name='question'),
        ),
        migrations.AlterField(
            model_name='installmentplan',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='package',
            name='active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='package',
            name='datetime_created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='package',
            name='price',
            field=models.PositiveIntegerField(db_index=True, default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='package',
            name='title',
            field=models.CharField(db_index=True, max_length=200, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='product',
            name='active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='product',
            name='author',
            field=models.CharField(blank=True, db_index=True, max_length=200, verbose_name='author'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('BUSINESS', 'BUSINESS'), ('ARCH_DESIGN', 'ARCH_DESIGN'), ('INTERIOR', 'INTERIOR'), ('URBAN', 'URBAN'), ('LANDSCAPE', 'LANDSCAPE'), ('DESIGN_GUIDE', 'DESIGN_GUIDE'), ('HISTORY', 'HISTORY'), ('DESIGN_BASICS', 'DESIGN_BASICS'), ('DIGITAL', 'DIGITAL'), ('SUSTAIN', 'SUSTAIN'), ('SAMPLES', 'SAMPLES'), ('OTHER', 'OTHER'), ('PACKAGES', 'PACKAGES')], db_index=True, default='OTHER', max_length=50, verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='datetime_created',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount_percent',
            field=models.PositiveSmallIntegerField(db_index=True, default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='discount percent'),
        ),
        migrations.AlterField(
            model_name='product',
            name='isbn',
            field=models.CharField(blank=True, db_index=True, max_length=30, verbose_name='isbn'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='publisher',
            field=models.CharField(blank=True, db_index=True, max_length=200, verbose_name='publisher'),
        ),
        migrations.AlterField(
            model_name='product',
            name='special_price',
            field=models.PositiveIntegerField(db_index=True, default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='special price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(db_index=True, max_length=200, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='productblog',
            name='blog_type',
            field=models.CharField(choices=[('ARTICLE', 'Article'), ('NEWS', 'News'), ('STORY', 'Story')], db_index=True, default='ARTICLE', max_length=20, verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='productblog',
            name='datetime_created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='productblog',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='productblog',
            name='title',
            field=models.CharField(db_index=True, max_length=200, verbose_name='title'),
        ),
        migrations.AlterUniqueTogether(
            name='tiereddiscount',
            unique_together={('user',)},
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['product', 'active'], name='products_co_product_33875a_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['author', 'active'], name='products_co_author__ed9d51_idx'),
        ),
        migrations.AddIndex(
            model_name='faq',
            index=models.Index(fields=['is_active', 'order'], name='products_fa_is_acti_5fe18d_idx'),
        ),
        migrations.AddIndex(
            model_name='installmentplan',
            index=models.Index(fields=['product', 'is_active'], name='products_in_product_807090_idx'),
        ),
        migrations.AddIndex(
            model_name='package',
            index=models.Index(fields=['active', 'price'], name='products_pa_active_ab23f5_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category', 'active'], name='products_pr_categor_748e0c_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['author', 'active'], name='products_pr_author_1d266c_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['discount_percent', 'special_price'], name='products_pr_discoun_1edb14_idx'),
        ),
        migrations.AddIndex(
            model_name='productblog',
            index=models.Index(fields=['product', 'is_active'], name='products_pr_product_8bd2b3_idx'),
        ),
        migrations.AddIndex(
            model_name='productblog',
            index=models.Index(fields=['blog_type', 'is_active'], name='products_pr_blog_ty_5aac73_idx'),
        ),
    ]
