# Generated by Django 6.0.2 on 2026-07-13 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_comment_active_alter_comment_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='categories',
            field=models.CharField(default=True, max_length=20, verbose_name='categories'),
        ),
    ]
