# Generated by Django 6.0.2 on 2026-09-24 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_optimize_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='wordpress_id',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True, unique=True, verbose_name='wordpress id'),
        ),
        migrations.AddField(
            model_name='product',
            name='wordpress_id',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True, unique=True, verbose_name='wordpress id'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('BUSINESS', 'کسب\u200cوکار معماری'), ('ARCH_DESIGN', 'معماری و طراحی'), ('INTERIOR', 'معماری داخلی'), ('URBAN', 'شهرسازی'), ('LANDSCAPE', 'منظر'), ('DESIGN_GUIDE', 'راهنمای طراحی'), ('HISTORY', 'تاریخ معماری'), ('DESIGN_BASICS', 'مبانی طراحی'), ('DIGITAL', 'دیجیتال و نرم\u200cافزار'), ('SUSTAIN', 'پایداری'), ('SAMPLES', 'نمونه\u200cها و پروژه\u200cها'), ('OTHER', 'سایر'), ('PACKAGES', 'بسته\u200cها')], db_index=True, default='OTHER', max_length=50, verbose_name='category'),
        ),
    ]
