# Generated by Django 6.0.2 on 2026-07-13 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_product_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='categories',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('history', 'history'), ('design_theory', 'design_theory'), ('sustainable', 'sustainable'), ('urban_planning', 'urban_planning'), ('misc', 'misc')], default='misc', max_length=20, verbose_name='Product Category'),
        ),
    ]
