# Generated by Django 6.0.2 on 2026-07-13 14:32

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_remove_product_categories_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='short_discription',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Product Short_Discription'),
        ),
    ]
