# Generated by Django 6.0.2 on 2026-07-15 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_alter_product_short_discription'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='author',
            field=models.CharField(blank=True, max_length=200, verbose_name='Author'),
        ),
        migrations.AddField(
            model_name='product',
            name='book_size',
            field=models.CharField(blank=True, choices=[('raghiei', 'raghiei'), ('vazehi', 'vazehi'), ('jeybi', 'jeybi'), ('rahlei', 'rahlei'), ('other', 'other')], max_length=20, null=True, verbose_name='Book Size'),
        ),
        migrations.AddField(
            model_name='product',
            name='cover_type',
            field=models.CharField(blank=True, choices=[('shomiz', 'shomiz'), ('salebi', 'salebi'), ('gard', 'gard'), ('other', 'other')], max_length=20, null=True, verbose_name='Cover Type'),
        ),
        migrations.AddField(
            model_name='product',
            name='edition',
            field=models.CharField(blank=True, max_length=50, verbose_name='Edition'),
        ),
        migrations.AddField(
            model_name='product',
            name='isbn',
            field=models.CharField(blank=True, max_length=20, verbose_name='ISBN'),
        ),
        migrations.AddField(
            model_name='product',
            name='pages',
            field=models.IntegerField(blank=True, null=True, verbose_name='Number of Pages'),
        ),
        migrations.AddField(
            model_name='product',
            name='publication_year',
            field=models.IntegerField(blank=True, null=True, verbose_name='Publication Year'),
        ),
        migrations.AddField(
            model_name='product',
            name='publisher',
            field=models.CharField(blank=True, max_length=200, verbose_name='Publisher'),
        ),
    ]
