# Generated by Django 6.0.2 on 2026-07-15 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_product_author_product_book_size_product_cover_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='short_discription',
        ),
    ]
