# Generated by Django 6.0.2 on 2026-07-16 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_remove_product_short_discription'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Printing_time',
            field=models.IntegerField(blank=True, null=True, verbose_name='Printing_time'),
        ),
        migrations.AlterField(
            model_name='product',
            name='cover_type',
            field=models.CharField(blank=True, choices=[('shomiz', 'shomiz'), ('gard', 'gard'), ('other', 'other')], max_length=20, null=True, verbose_name='Cover Type'),
        ),
    ]
