# Generated by Django 6.0.2 on 2026-07-16 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_product_printing_time_alter_product_cover_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Printing_time',
            field=models.CharField(blank=True, null=True, verbose_name='Printing_time'),
        ),
    ]
