# Generated by Django 6.0.2 on 2026-07-17 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_alter_product_printing_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('HISTBusiness_and_Managemen', 'HISTBusiness_and_Managemen'), ('Architectural_design', 'Architectural_design'), ('Interior_design_and_architecture', 'Interior_design_and_architecture'), ('Urban_studies_and_design', 'Urban_studies_and_design'), ('View', 'View'), ('Design_Guide', 'Design_Guide'), ('History_Criticism_and_Theory', 'History_Criticism_and_Theory'), ('VExpression_Basics_and_Design_Conceptsiew', 'VExpression_Basics_and_Design_Conceptsiew'), ('Digital_and_parametric_design', 'Digital_and_parametric_design'), ('Sustainability_and_naturalismView', 'Sustainability_and_naturalismView'), ('Project_sample', 'Project_sample'), ('Other_books', 'Other_books'), ('Packages_and_Sets', 'Packages_and_Sets')], max_length=45, verbose_name='Product Category'),
        ),
    ]
