# Generated by Django 6.0.2 on 2026-07-17 09:02

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='book_size',
            field=models.CharField(blank=True, choices=[('raghiei', 'رقعی'), ('vazehi', 'وزیری'), ('jeybi', 'جیبی'), ('rahlei', 'رحلی'), ('other', 'سایر')], max_length=20, null=True, verbose_name='Book Size'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('BUSINESS_MANAGEMENT', 'کسب\u200cوکار و مدیریت'), ('ARCHITECTURAL_DESIGN', 'طراحی معماری'), ('INTERIOR_DESIGN', 'طراحی و معماری داخلی'), ('URBAN_STUDIES', 'مطالعات و طراحی شهری'), ('LANDSCAPE', 'منظر (لنداسکیپ)'), ('DESIGN_GUIDE', 'راهنمای طراحی'), ('HISTORY_CRITICISM', 'تاریخ، نقد و نظریه'), ('DESIGN_FUNDAMENTALS', 'بیان، مقدمات و مفاهیم طراحی'), ('DIGITAL_PARAMETRIC', 'طراحی دیجیتال و پارامتریک'), ('SUSTAINABILITY', 'پایداری و طبیعت\u200cگرایی'), ('PROJECT_SAMPLES', 'نمونه پروژه'), ('OTHER', 'سایر کتاب\u200cها'), ('PACKAGES', 'بسته\u200cها و مجموعه\u200cها')], default='OTHER', max_length=30, verbose_name='Product Category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='cover_type',
            field=models.CharField(blank=True, choices=[('shomiz', 'شومیز'), ('gard', 'گالینگور'), ('other', 'سایر')], max_length=20, null=True, verbose_name='Cover Type'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=ckeditor.fields.RichTextField(verbose_name='Product Description'),
        ),
    ]
