# Generated by Django 6.0.2 on 2026-07-17 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('BUSINESS_MANAGEMENT', 'کسب\u200cوکار و مدیریت'), ('ARCHITECTURAL_DESIGN', 'طراحی معماری'), ('INTERIOR_DESIGN', 'طراحی و معماری داخلی'), ('URBAN_STUDIES', 'مطالعات و طراحی شهری'), ('LANDSCAPE', 'منظر (لنداسکیپ)'), ('DESIGN_GUIDE', 'راهنمای طراحی'), ('HISTORY_CRITICISM', 'تاریخ، نقد و نظریه'), ('DESIGN_FUNDAMENTALS', 'بیان، مقدمات و مفاهیم طراحی'), ('DIGITAL_PARAMETRIC', 'طراحی دیجیتال و پارامتریک'), ('SUSTAINABILITY', 'پایداری و طبیعت\u200cگرایی'), ('PROJECT_SAMPLES', 'نمونه پروژه'), ('OTHER', 'سایر کتاب\u200cها'), ('PACKAGES', 'بسته\u200cها و مجموعه\u200cها')], default='OTHER', max_length=100, verbose_name='Product Category'),
        ),
    ]
