# Generated by Django 6.0.2 on 2026-07-17 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('BUSINESS', 'کسب\u200cوکار و مدیریت'), ('ARCH_DESIGN', 'طراحی معماری'), ('INTERIOR', 'طراحی و معماری داخلی'), ('URBAN', 'مطالعات و طراحی شهری'), ('LANDSCAPE', 'منظر (لنداسکیپ)'), ('DESIGN_GUIDE', 'راهنمای طراحی'), ('HISTORY', 'تاریخ، نقد و نظریه'), ('DESIGN_BASICS', 'بیان، مقدمات و مفاهیم طراحی'), ('DIGITAL', 'طراحی دیجیتال و پارامتریک'), ('SUSTAIN', 'پایداری و طبیعت\u200cگرایی'), ('SAMPLES', 'نمونه پروژه'), ('OTHER', 'سایر کتاب\u200cها'), ('PACKAGES', 'بسته\u200cها و مجموعه\u200cها')], default='OTHER', max_length=20, verbose_name='Product Category'),
        ),
    ]
