# Generated by Django 6.0.2 on 2026-07-17 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('BUSINESS', 'BUSINESS'), ('ARCH_DESIGN', 'ARCH_DESIGN'), ('INTERIOR', 'INTERIOR'), ('URBAN', 'URBAN'), ('LANDSCAPE', 'LANDSCAPE'), ('DESIGN_GUIDE', 'DESIGN_GUIDE'), ('HISTORY', 'HISTORY'), ('DESIGN_BASICS', 'DESIGN_BASICS'), ('DIGITAL', 'DIGITAL'), ('SUSTAIN', 'SUSTAIN'), ('SAMPLES', 'SAMPLES'), ('OTHER', 'OTHER'), ('PACKAGES', 'PACKAGES')], default='OTHER', max_length=20, verbose_name='Product Category'),
        ),
    ]
