# Generated by Django 6.0.2 on 2026-07-21 09:22

import ckeditor.fields
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_alter_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Printing_time',
        ),
        migrations.RemoveField(
            model_name='product',
            name='pages',
        ),
        migrations.RemoveField(
            model_name='product',
            name='publication_year',
        ),
        migrations.AddField(
            model_name='product',
            name='Publication_date',
            field=models.IntegerField(blank=True, null=True, verbose_name='Publication_date'),
        ),
        migrations.AddField(
            model_name='product',
            name='number_of_pages',
            field=models.IntegerField(blank=True, null=True, verbose_name='number_of_pages'),
        ),
        migrations.AddField(
            model_name='product',
            name='printing_series',
            field=models.IntegerField(blank=True, null=True, verbose_name='printing_series'),
        ),
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.IntegerField(blank=True, null=True, verbose_name='weight'),
        ),
        migrations.AddField(
            model_name='product',
            name='year_of_publication',
            field=models.IntegerField(blank=True, null=True, verbose_name='year_of_publication'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='body',
            field=models.TextField(verbose_name='Comment_Text'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='stars',
            field=models.IntegerField(choices=[(1, 'Very_Bad'), (2, 'Bad'), (3, 'Normal'), (4, 'Good'), (5, 'Perfect')], verbose_name='What_is_your_score?'),
        ),
        migrations.AlterField(
            model_name='product',
            name='active',
            field=models.BooleanField(default=True, verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='product',
            name='author',
            field=models.CharField(blank=True, max_length=200, verbose_name='author'),
        ),
        migrations.AlterField(
            model_name='product',
            name='book_size',
            field=models.CharField(blank=True, choices=[('raghiei', 'رقعی'), ('vazehi', 'وزیری'), ('jeybi', 'جیبی'), ('rahlei', 'رحلی'), ('other', 'سایر')], max_length=20, null=True, verbose_name='book_size'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('BUSINESS', 'BUSINESS'), ('ARCH_DESIGN', 'ARCH_DESIGN'), ('INTERIOR', 'INTERIOR'), ('URBAN', 'URBAN'), ('LANDSCAPE', 'LANDSCAPE'), ('DESIGN_GUIDE', 'DESIGN_GUIDE'), ('HISTORY', 'HISTORY'), ('DESIGN_BASICS', 'DESIGN_BASICS'), ('DIGITAL', 'DIGITAL'), ('SUSTAIN', 'SUSTAIN'), ('SAMPLES', 'SAMPLES'), ('OTHER', 'OTHER'), ('PACKAGES', 'PACKAGES')], default='OTHER', max_length=20, verbose_name='Product_Category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='cover_type',
            field=models.CharField(blank=True, choices=[('shomiz', 'شومیز'), ('gard', 'گالینگور'), ('other', 'سایر')], max_length=20, null=True, verbose_name='cover_type'),
        ),
        migrations.AlterField(
            model_name='product',
            name='datetime_created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='datetime_created'),
        ),
        migrations.AlterField(
            model_name='product',
            name='datetime_modified',
            field=models.DateTimeField(auto_now=True, verbose_name='datetime_modified'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=ckeditor.fields.RichTextField(verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='edition',
            field=models.CharField(blank=True, max_length=50, verbose_name='edition'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to='product/product_cover/', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='product',
            name='isbn',
            field=models.CharField(blank=True, max_length=20, verbose_name='isbn'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.PositiveIntegerField(default=0, verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='publisher',
            field=models.CharField(blank=True, max_length=200, verbose_name='publisher'),
        ),
    ]
