# Generated by Django 6.0.2 on 2026-07-21 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0024_remove_product_printing_time_remove_product_pages_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('BUSINESS', 'BUSINESS'), ('ARCH_DESIGN', 'ARCH_DESIGN'), ('INTERIOR', 'INTERIOR'), ('URBAN', 'URBAN'), ('LANDSCAPE', 'LANDSCAPE'), ('DESIGN_GUIDE', 'DESIGN_GUIDE'), ('HISTORY', 'HISTORY'), ('DESIGN_BASICS', 'DESIGN_BASICS'), ('DIGITAL', 'DIGITAL'), ('SUSTAIN', 'SUSTAIN'), ('SAMPLES', 'SAMPLES'), ('OTHER', 'OTHER'), ('PACKAGES', 'PACKAGES')], default='OTHER', max_length=20, verbose_name='product_category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=100, verbose_name='product_title'),
        ),
    ]
