# Generated by Django 6.0.2 on 2026-07-22 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0025_alter_product_category_alter_product_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Publication_date',
            field=models.IntegerField(blank=True, null=True, verbose_name='publication_date'),
        ),
    ]
