# Generated by Django 6.0.2 on 2026-07-22 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0026_alter_product_publication_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Publication_date',
            new_name='publication_date',
        ),
    ]
