# Generated by Django 6.0.2 on 2026-07-22 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0027_rename_publication_date_product_publication_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='printing_series',
            field=models.CharField(blank=True, null=True, verbose_name='printing_series'),
        ),
    ]
