# Generated by Django 6.0.2 on 2026-07-23 14:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0028_alter_product_printing_series'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('slug', models.SlugField(allow_unicode=True, max_length=200, unique=True, verbose_name='slug')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('image', models.ImageField(blank=True, null=True, upload_to='packages/', verbose_name='image')),
                ('price', models.DecimalField(decimal_places=2, help_text='Total price for this package', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='price')),
                ('original_price', models.DecimalField(blank=True, decimal_places=2, help_text='Sum of all product prices (auto-calculated)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='original price')),
                ('discount_percent', models.PositiveSmallIntegerField(default=0, help_text='Discount percentage for this package', verbose_name='discount percent')),
                ('active', models.BooleanField(default=True, verbose_name='active')),
                ('datetime_created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('datetime_modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('products', models.ManyToManyField(limit_choices_to={'active': True}, related_name='packages', to='products.product', verbose_name='products')),
            ],
            options={
                'verbose_name': 'package',
                'verbose_name_plural': 'packages',
                'ordering': ['-datetime_created'],
            },
        ),
    ]
