# Generated by Django 6.0.2 on 2026-07-23 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0029_package'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='stock',
            field=models.PositiveIntegerField(default=0, help_text='Available stock for this package', verbose_name='stock'),
        ),
    ]
