# Generated by Django 6.0.2 on 2026-07-26 08:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0030_package_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='manual_price',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, help_text='Enter manual price if you want to override auto-calculation', max_digits=10, null=True, verbose_name='manual price'),
        ),
        migrations.AlterField(
            model_name='package',
            name='discount_percent',
            field=models.PositiveSmallIntegerField(default=0, help_text='Discount percentage (if set, price will be auto-calculated)', verbose_name='discount percent'),
        ),
        migrations.AlterField(
            model_name='package',
            name='original_price',
            field=models.DecimalField(decimal_places=0, default=0, help_text='Sum of all product prices (auto-calculated)', max_digits=10, verbose_name='original price'),
        ),
        migrations.AlterField(
            model_name='package',
            name='price',
            field=models.DecimalField(decimal_places=0, default=0, help_text='Final price (auto-calculated from discount or enter manually)', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='package',
            name='products',
            field=models.ManyToManyField(blank=True, limit_choices_to={'active': True}, related_name='packages', to='products.product', verbose_name='products'),
        ),
    ]
