# Generated by Django 6.0.2 on 2026-07-26 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0031_package_manual_price_alter_package_discount_percent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='manual_price',
            field=models.PositiveIntegerField(default=0, verbose_name='manual price'),
        ),
        migrations.AlterField(
            model_name='package',
            name='original_price',
            field=models.PositiveIntegerField(default=0, verbose_name='original price'),
        ),
        migrations.AlterField(
            model_name='package',
            name='price',
            field=models.PositiveIntegerField(default=0, verbose_name='price'),
        ),
    ]
