# Generated by Django 6.0.2 on 2026-08-04 13:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0032_alter_package_manual_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='manual_price',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='manual price'),
        ),
        migrations.AlterField(
            model_name='package',
            name='original_price',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='original price'),
        ),
        migrations.AlterField(
            model_name='package',
            name='price',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='package',
            name='stock',
            field=models.PositiveIntegerField(default=0, help_text='Available stock for this package', validators=[django.core.validators.MinValueValidator(0)], verbose_name='stock'),
        ),
    ]
