# Generated by Django 6.0.2 on 2026-08-07 18:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0033_alter_package_manual_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount_end_date',
            field=models.DateTimeField(blank=True, help_text='زمان پایان تخفیف', null=True, verbose_name='discount end date'),
        ),
        migrations.AddField(
            model_name='product',
            name='discount_percent',
            field=models.PositiveSmallIntegerField(default=0, help_text='درصد تخفیف (0 تا 100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='discount percent'),
        ),
        migrations.AddField(
            model_name='product',
            name='discount_start_date',
            field=models.DateTimeField(blank=True, help_text='زمان شروع تخفیف', null=True, verbose_name='discount start date'),
        ),
        migrations.AddField(
            model_name='product',
            name='special_price',
            field=models.PositiveIntegerField(default=0, help_text='قیمت ویژه (اگر وارد شود، تخفیف به صورت مبلغ ثابت اعمال می\u200cشود)', validators=[django.core.validators.MinValueValidator(0)], verbose_name='special price'),
        ),
    ]
