# Generated by Django 6.0.2 on 2026-08-08 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0034_product_discount_end_date_product_discount_percent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='printing_series',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='printing_series'),
        ),
    ]
